import Header from "@/components/Header";
import "./global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <footer style={{ background: "green" }}>Footer</footer>
      </body>
    </html>
  );
}
