import Header from "@/components/Header";
import "./global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  // const indexError = Math.round(Math.random());
  // // console.log("🚀 ~ indexError:", indexError);

  // if (indexError === 0) {
  //   throw new Error("AI Error");
  // }

  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
        <footer>Footer</footer>
      </body>
    </html>
  );
}
